// Generated by pdfx init.
// See: https://pdfx.akashpise.dev/installation#theming
//
// Provides runtime theme overrides via React context.
// Wrap a subtree in <PdfxThemeProvider theme={myTheme}> to override defaults.
//
// Note: PDFs are rendered server-side via @react-pdf/renderer (renderToBuffer),
// where React Context is not propagated and Next.js forbids createContext in
// server modules. These helpers therefore return the default theme directly.

/* eslint-disable react-refresh/only-export-components */
// Intentional: this module exports both a component and hooks.
// Keeping a single import surface preserves the generated public API.

import { type DependencyList, type ReactNode } from 'react';
import { theme as defaultTheme } from './pdfx-theme';

type PdfxTheme = typeof defaultTheme;

export interface PdfxThemeProviderProps {
  theme?: PdfxTheme;
  children: ReactNode;
}

export function PdfxThemeProvider({ theme, children }: PdfxThemeProviderProps) {
  // No-op provider: server-rendered PDFs always use the default theme.
  // Kept for API compatibility with the generated pdfx public surface.
  void theme;
  return <>{children}</>;
}

/**
 * Returns the active theme.
 *
 * PDFs are rendered headlessly on the server (e.g. @react-pdf/renderer
 * renderToBuffer), so the default theme is always returned.
 */
export function usePdfxTheme(): PdfxTheme {
  return defaultTheme;
}

/**
 * Calls factory() and returns the result.
 * The deps parameter is accepted for API compatibility with existing callers.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function useSafeMemo<T>(factory: () => T, _deps: DependencyList): T {
  return factory();
}
