import type { OnboardingStep, OnboardingFlow, OnboardingRole } from "./types";
import {
  validateBrandProfileExists,
  validateBranchesExist,
  validateAccountsExist,
  validatePaymentAccountsExist,
  validatePaymentMethodsExist,
  validateTechniciansExist,
  validateFrontlinersExist,
  validateSparepartsExist,
  validateCustomersExist,
  validateServicesExist,
} from "@/server/actions/onboarding-v2.actions";

function makeValidator(fn: (slug: string) => Promise<{ success: boolean; exists: boolean }>, brandSlug: string) {
  return async () => {
    const result = await fn(brandSlug);
    return result.exists;
  };
}

export function getOnboardingFlow(role: OnboardingRole, brandSlug: string): OnboardingFlow {
  const flows: Record<OnboardingRole, OnboardingStep[]> = {
    MASTER_ADMIN: getMasterAdminFlow(brandSlug),
    ADMIN: getAdminFlow(brandSlug),
    FRONTLINER: getFrontlinerFlow(brandSlug),
    TECHNICIAN: getTechnicianFlow(brandSlug),
    CASHIER: getCashierFlow(brandSlug),
  };
  return { role, steps: flows[role] ?? [] };
}

function getMasterAdminFlow(brandSlug: string): OnboardingStep[] {
  return [
    {
      id: "welcome",
      label: "Selamat Datang",
      description: "Mari kita lakukan setup awal agar operasional toko siap digunakan.",
      ctaLabel: "Mulai Setup",
      ctaHref: `/${brandSlug}/panel/dashboard`,
      validator: async () => false,
      side: "bottom",
      sideOffset: 16,
    },
    {
      id: "brand-profile",
      label: "Brand Profile",
      description: "Lengkapi profil brand: logo, nama, alamat, dan kontak toko Anda.",
      pageInstructions: [
        "Isi nama brand, alamat, dan kontak toko Anda",
        "Upload logo toko (opsional)",
        "Klik Simpan setelah selesai",
      ],
      ctaLabel: "Buka Brand Profile",
      ctaHref: `/${brandSlug}/panel/settings`,
      targetSelector: "button:has(.lucide-save)",
      dataTourStepId: "brand-profile",
      validator: makeValidator(validateBrandProfileExists, brandSlug),
      side: "right",
      sideOffset: 16,
    },
    {
      id: "cabang",
      label: "Cabang",
      description: "Cabang digunakan untuk memisahkan transaksi, stok, dan laporan antar lokasi.",
      pageInstructions: [
        'Klik tombol "Tambah Cabang"',
        "Isi nama cabang dan alamat",
        "Klik Simpan untuk menyimpan cabang baru",
      ],
      ctaLabel: "Tambah Cabang",
      ctaHref: `/${brandSlug}/panel/branches`,
      targetSelector: "button:has(.lucide-plus)",
      dataTourStepId: "branches",
      validator: makeValidator(validateBranchesExist, brandSlug),
      side: "right",
      sideOffset: 16,
    },
    {
      id: "account",
      label: "Account",
      description: "Setiap cabang membutuhkan Admin dan Frontliner untuk menjalankan operasional.",
      pageInstructions: [
        'Klik tombol "Tambah User"',
        "Pilih role (Admin atau Frontliner) dan isi data user",
        "Klik Simpan untuk membuat akun baru",
      ],
      ctaLabel: "Tambah Account",
      ctaHref: `/${brandSlug}/panel/accounts`,
      targetSelector: "button:has(.lucide-plus)",
      dataTourStepId: "users",
      validator: makeValidator(validateAccountsExist, brandSlug),
      side: "right",
      sideOffset: 16,
    },
    {
      id: "payment-account",
      label: "Akun Pembayaran",
      description: "Hubungkan rekening perusahaan untuk menerima pembayaran dari pelanggan.",
      pageInstructions: [
        'Klik tombol "Tambah Akun"',
        "Pilih bank dan masukkan nomor rekening",
        "Klik Simpan untuk menambahkan akun pembayaran",
      ],
      ctaLabel: "Tambah Akun Pembayaran",
      ctaHref: `/${brandSlug}/panel/payment-accounts`,
      targetSelector: "button:has(.lucide-plus)",
      dataTourStepId: "payment-accounts",
      validator: makeValidator(validatePaymentAccountsExist, brandSlug),
      side: "right",
      sideOffset: 16,
    },
    {
      id: "payment-method",
      label: "Metode Pembayaran",
      description: "Aktifkan QRIS, Cash, Transfer, Midtrans, dan metode pembayaran lainnya.",
      pageInstructions: [
        'Klik tombol "Tambah" atau aktifkan metode pembayaran yang tersedia',
        "Konfigurasi QRIS, Transfer, atau metode lainnya",
        "Pastikan minimal satu metode aktif untuk menerima pembayaran",
      ],
      ctaLabel: "Kelola Metode Pembayaran",
      ctaHref: `/${brandSlug}/panel/payment-methods`,
      targetSelector: "button:has(.lucide-plus)",
      dataTourStepId: "payment-methods",
      validator: makeValidator(validatePaymentMethodsExist, brandSlug),
      side: "right",
      sideOffset: 16,
    },
    {
      id: "finish",
      label: "Setup Selesai",
      description: "Sekarang Anda siap menggunakan Seervisio!",
      ctaLabel: "Masuk Dashboard",
      ctaHref: `/${brandSlug}/panel/dashboard`,
      validator: async () => true,
      side: "bottom",
      sideOffset: 16,
    },
  ];
}

function getAdminFlow(brandSlug: string): OnboardingStep[] {
  return [
    {
      id: "welcome",
      label: "Selamat Datang",
      description: "Mari kita siapkan tim dan inventaris toko.",
      ctaLabel: "Mulai",
      ctaHref: `/${brandSlug}/panel/dashboard`,
      validator: async () => false,
      side: "bottom",
      sideOffset: 16,
    },
    {
      id: "technician",
      label: "Tambah Teknisi",
      description: "Tambahkan teknisi untuk menangani servis pelanggan.",
      pageInstructions: [
        "Pastikan filter role sudah benar (TECHNICIAN)",
        'Klik tombol "Tambah User"',
        "Isi nama, email, password, dan pilih cabang",
        "Klik Simpan untuk membuat akun teknisi",
      ],
      ctaLabel: "Tambah Teknisi",
      ctaHref: `/${brandSlug}/panel/accounts`,
      targetSelector: "button:has(.lucide-plus)",
      dataTourStepId: "users",
      validator: makeValidator(validateTechniciansExist, brandSlug),
      side: "right",
      sideOffset: 16,
    },
    {
      id: "frontliner",
      label: "Tambah Frontliner",
      description: "Frontliner membantu menerima pelanggan dan mengelola antrian.",
      pageInstructions: [
        "Pastikan filter role sudah benar (FRONTLINER)",
        'Klik tombol "Tambah User"',
        "Isi nama, email, password, dan pilih cabang",
        "Klik Simpan untuk membuat akun frontliner",
      ],
      ctaLabel: "Tambah Frontliner",
      ctaHref: `/${brandSlug}/panel/accounts`,
      targetSelector: "button:has(.lucide-plus)",
      dataTourStepId: "users",
      validator: makeValidator(validateFrontlinersExist, brandSlug),
      side: "right",
      sideOffset: 16,
    },
    {
      id: "sparepart",
      label: "Tambah Sparepart",
      description: "Masukkan stok sparepart yang sering digunakan untuk servis.",
      pageInstructions: [
        'Klik tombol "Tambah Stok" untuk menambahkan produk baru',
        "Pilih kategori Sparepart dan isi detail produk",
        "Atur harga jual dan jumlah stok awal",
        "Klik Simpan untuk menyimpan sparepart",
      ],
      ctaLabel: "Tambah Sparepart",
      ctaHref: `/${brandSlug}/panel/inventory-v4`,
      targetSelector: "button:has(.lucide-plus)",
      dataTourStepId: "inventory",
      validator: makeValidator(validateSparepartsExist, brandSlug),
      side: "right",
      sideOffset: 16,
    },
    {
      id: "finish",
      label: "Setup Selesai",
      description: "Tim dan inventaris sudah siap. Selamat bekerja!",
      ctaLabel: "Masuk Dashboard",
      ctaHref: `/${brandSlug}/panel/dashboard`,
      validator: async () => true,
      side: "bottom",
      sideOffset: 16,
    },
  ];
}

function getFrontlinerFlow(brandSlug: string): OnboardingStep[] {
  return [
    {
      id: "welcome",
      label: "Selamat Datang",
      description: "Pelajari cara melayani pelanggan dengan Seervisio.",
      ctaLabel: "Mulai",
      ctaHref: `/${brandSlug}/panel/dashboard`,
      validator: async () => false,
      side: "bottom",
      sideOffset: 16,
    },
    {
      id: "pelanggan",
      label: "Tambah Pelanggan",
      description: "Catat data pelanggan sebelum membuat servis.",
      pageInstructions: [
        "Halaman daftar pelanggan menampilkan semua data pelanggan",
        "Pelanggan bisa ditambahkan saat membuat servis baru",
        "Cukup buka halaman Services untuk memulai",
      ],
      ctaLabel: "Tambah Pelanggan",
      ctaHref: `/${brandSlug}/panel/customers`,
      dataTourStepId: "customers",
      validator: makeValidator(validateCustomersExist, brandSlug),
      side: "right",
      sideOffset: 16,
    },
    {
      id: "servis",
      label: "Tambah Servis",
      description: "Buat servis baru untuk pelanggan yang datang.",
      pageInstructions: [
        'Klik tombol "Buat Servis Baru" di sidebar kanan',
        "Pilih atau daftarkan pelanggan baru",
        "Isi detail perangkat dan keluhan",
        "Klik Buat Servis untuk menyimpan",
      ],
      ctaLabel: "Buat Servis",
      ctaHref: `/${brandSlug}/panel/services`,
      targetSelector: "button:has(.lucide-plus)",
      dataTourStepId: "services",
      validator: makeValidator(validateServicesExist, brandSlug),
      side: "right",
      sideOffset: 16,
    },
    {
      id: "tracking",
      label: "Tracking Servis",
      description: "Pantau status servis pelanggan secara real-time dari halaman ini.",
      ctaLabel: "Lihat Servis",
      ctaHref: `/${brandSlug}/panel/services`,
      dataTourStepId: "services",
      validator: async () => true,
      side: "right",
      sideOffset: 16,
    },
    {
      id: "pos",
      label: "POS",
      description: "Gunakan POS untuk mencatat penjualan produk dan sparepart.",
      ctaLabel: "Buka POS",
      ctaHref: `/${brandSlug}/panel/pos-v4`,
      dataTourStepId: "pos",
      validator: async () => true,
      side: "right",
      sideOffset: 16,
    },
    {
      id: "finish",
      label: "Selesai",
      description: "Anda siap melayani pelanggan!",
      ctaLabel: "Ke Dashboard",
      ctaHref: `/${brandSlug}/panel/dashboard`,
      validator: async () => true,
      side: "bottom",
      sideOffset: 16,
    },
  ];
}

function getTechnicianFlow(brandSlug: string): OnboardingStep[] {
  return [
    {
      id: "welcome",
      label: "Selamat Datang",
      description: "Pelajari alur kerja teknisi di Seervisio.",
      ctaLabel: "Mulai",
      ctaHref: `/${brandSlug}/panel/dashboard`,
      validator: async () => false,
      side: "bottom",
      sideOffset: 16,
    },
    {
      id: "antrian",
      label: "Antrian Servis",
      description: "Lihat daftar servis yang menunggu untuk ditangani.",
      ctaLabel: "Lihat Antrian",
      ctaHref: `/${brandSlug}/panel/services`,
      dataTourStepId: "services",
      validator: async () => true,
      side: "right",
      sideOffset: 16,
    },
    {
      id: "diagnosa",
      label: "Diagnosa",
      description: "Lakukan diagnosa pada perangkat pelanggan dan catat temuan.",
      ctaLabel: "Buka Servis",
      ctaHref: `/${brandSlug}/panel/services`,
      dataTourStepId: "services",
      validator: async () => true,
      side: "right",
      sideOffset: 16,
    },
    {
      id: "status",
      label: "Update Status",
      description: "Perbarui status servis seiring progres pengerjaan.",
      ctaLabel: "Lihat Servis",
      ctaHref: `/${brandSlug}/panel/services`,
      dataTourStepId: "services",
      validator: async () => true,
      side: "right",
      sideOffset: 16,
    },
    {
      id: "qc",
      label: "Quality Check",
      description: "Pastikan kualitas sebelum servis siap diambil pelanggan.",
      ctaLabel: "Lanjut",
      ctaHref: `/${brandSlug}/panel/services`,
      dataTourStepId: "services",
      validator: async () => true,
      side: "right",
      sideOffset: 16,
    },
    {
      id: "pickup",
      label: "Siap Diambil",
      description: "Tandai servis yang sudah selesai dan siap diambil pelanggan.",
      ctaLabel: "Selesai",
      ctaHref: `/${brandSlug}/panel/services`,
      dataTourStepId: "services",
      validator: async () => true,
      side: "right",
      sideOffset: 16,
    },
    {
      id: "finish",
      label: "Selesai",
      description: "Anda siap menangani servis pelanggan!",
      ctaLabel: "Ke Dashboard",
      ctaHref: `/${brandSlug}/panel/dashboard`,
      validator: async () => true,
      side: "bottom",
      sideOffset: 16,
    },
  ];
}

function getCashierFlow(brandSlug: string): OnboardingStep[] {
  return [
    {
      id: "welcome",
      label: "Selamat Datang",
      description: "Pelajari cara menggunakan POS dan pembayaran.",
      ctaLabel: "Mulai",
      ctaHref: `/${brandSlug}/panel/dashboard`,
      validator: async () => false,
      side: "bottom",
      sideOffset: 16,
    },
    {
      id: "pos",
      label: "POS",
      description: "Gunakan POS untuk mencatat penjualan dan pembayaran.",
      ctaLabel: "Buka POS",
      ctaHref: `/${brandSlug}/panel/pos-v4`,
      dataTourStepId: "pos",
      validator: async () => true,
      side: "right",
      sideOffset: 16,
    },
    {
      id: "pembayaran",
      label: "Pembayaran",
      description: "Terima pembayaran dari pelanggan melalui berbagai metode.",
      ctaLabel: "Buka Pembayaran",
      ctaHref: `/${brandSlug}/panel/services`,
      dataTourStepId: "services",
      validator: async () => true,
      side: "right",
      sideOffset: 16,
    },
    {
      id: "shift",
      label: "Shift",
      description: "Buka shift sebelum memulai transaksi dan tutup shift di akhir.",
      ctaLabel: "Buka Shift",
      ctaHref: `/${brandSlug}/panel/store-shift`,
      dataTourStepId: "store-shift",
      validator: async () => true,
      side: "right",
      sideOffset: 16,
    },
    {
      id: "laporan",
      label: "Laporan",
      description: "Cek laporan pendapatan dan transaksi harian.",
      ctaLabel: "Lihat Laporan",
      ctaHref: `/${brandSlug}/panel/finance`,
      dataTourStepId: "finance",
      validator: async () => true,
      side: "right",
      sideOffset: 16,
    },
    {
      id: "finish",
      label: "Selesai",
      description: "Anda siap menggunakan POS!",
      ctaLabel: "Ke Dashboard",
      ctaHref: `/${brandSlug}/panel/dashboard`,
      validator: async () => true,
      side: "bottom",
      sideOffset: 16,
    },
  ];
}
