import React from "react";
import { View, Text, StyleSheet } from "@react-pdf/renderer";
import { theme } from "@/lib/pdfx-theme";
import { PdfPageNumber } from "@/components/pdfx/page-number/pdfx-page-number";

interface PdfFooterProps {
  leftText?: string;
  centerText?: string;
  showPageNumber?: boolean;
  showTimestamp?: boolean;
  timestamp?: string;
  fixed?: boolean;
  sticky?: boolean;
}

const styles = StyleSheet.create({
  container: {
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  left: {
    fontSize: theme.primitives.typography.xs,
    color: theme.colors.mutedForeground,
  },
  center: {
    fontSize: theme.primitives.typography.xs,
    color: theme.colors.mutedForeground,
    textAlign: "center",
    flex: 1,
  },
  pageNumberContainer: {
    alignItems: "flex-end",
  },
  timestamp: {
    fontSize: theme.primitives.typography.xs,
    color: theme.colors.mutedForeground,
    marginTop: 2,
  },
});

export function PdfFooter({
  leftText = "Generated by Seervisio",
  centerText,
  showPageNumber = true,
  showTimestamp = true,
  timestamp,
  fixed,
  sticky,
}: PdfFooterProps) {
  const ts = timestamp || new Date().toLocaleString("id-ID", {
    day: "2-digit", month: "long", year: "numeric",
    hour: "2-digit", minute: "2-digit",
  });

  return (
    <View
      style={styles.container}
      fixed={fixed}
    >
      <View style={styles.row}>
        <Text style={styles.left}>{leftText}</Text>
        {centerText && (
          <Text style={styles.center}>{centerText}</Text>
        )}
        {showPageNumber && (
          <View style={styles.pageNumberContainer}>
            <PdfPageNumber
              format="Page {page} of {total}"
              size="xs"
              muted
              fixed={false}
            />
          </View>
        )}
      </View>
      {showTimestamp && (
        <Text style={styles.timestamp}>{ts}</Text>
      )}
    </View>
  );
}
