import React from "react";
import { View, Text, StyleSheet } from "@react-pdf/renderer";
import { theme } from "@/lib/pdfx-theme";

interface PdfHeaderProps {
  title: string;
  subtitle?: string;
  brandName?: string | null;
  branchName?: string | null;
  generatedBy?: string | null;
  generatedAt?: string;
  period?: string;
  rightText?: string;
  rightSubText?: string;
  showDivider?: boolean;
}

const styles = StyleSheet.create({
  container: {
    marginBottom: theme.spacing.sectionGap,
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  left: {
    flex: 1,
  },
  right: {
    alignItems: "flex-end",
  },
  brandName: {
    fontFamily: theme.typography.heading.fontFamily,
    fontSize: theme.primitives.typography.xs,
    color: theme.colors.mutedForeground,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  title: {
    fontFamily: theme.typography.heading.fontFamily,
    fontSize: theme.typography.heading.fontSize.h2,
    fontWeight: theme.typography.heading.fontWeight,
    color: theme.colors.foreground,
    lineHeight: theme.typography.heading.lineHeight,
  },
  subtitle: {
    fontSize: theme.primitives.typography.sm,
    color: theme.colors.mutedForeground,
    marginTop: 3,
  },
  rightText: {
    fontFamily: theme.typography.heading.fontFamily,
    fontSize: theme.primitives.typography.lg,
    color: theme.colors.foreground,
  },
  rightSubText: {
    fontSize: theme.primitives.typography.xs,
    color: theme.colors.mutedForeground,
    marginTop: 2,
  },
  meta: {
    flexDirection: "row",
    gap: 24,
    marginTop: 8,
  },
  metaItem: {
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
  },
  metaLabel: {
    fontSize: theme.primitives.typography.xs,
    color: theme.colors.mutedForeground,
  },
  metaValue: {
    fontSize: theme.primitives.typography.xs,
    color: theme.colors.foreground,
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.border,
    marginTop: theme.spacing.componentGap,
  },
});

export function PdfHeader({
  title,
  subtitle,
  brandName,
  branchName,
  generatedBy,
  generatedAt,
  period,
  rightText,
  rightSubText,
  showDivider = true,
}: PdfHeaderProps) {
  return (
    <View style={styles.container}>
      <View style={styles.topRow}>
        <View style={styles.left}>
          {brandName && (
            <Text style={styles.brandName}>{brandName}</Text>
          )}
          <Text style={styles.title}>{title}</Text>
          {subtitle && (
            <Text style={styles.subtitle}>{subtitle}</Text>
          )}
        </View>
        {(rightText || rightSubText) && (
          <View style={styles.right}>
            {rightText && <Text style={styles.rightText}>{rightText}</Text>}
            {rightSubText && <Text style={styles.rightSubText}>{rightSubText}</Text>}
          </View>
        )}
      </View>

      {(branchName || generatedBy || generatedAt || period) && (
        <View style={styles.meta}>
          {branchName && (
            <View style={styles.metaItem}>
              <Text style={styles.metaLabel}>Branch:</Text>
              <Text style={styles.metaValue}>{branchName}</Text>
            </View>
          )}
          {generatedBy && (
            <View style={styles.metaItem}>
              <Text style={styles.metaLabel}>Generated by:</Text>
              <Text style={styles.metaValue}>{generatedBy}</Text>
            </View>
          )}
          {generatedAt && (
            <View style={styles.metaItem}>
              <Text style={styles.metaLabel}>Date:</Text>
              <Text style={styles.metaValue}>{generatedAt}</Text>
            </View>
          )}
          {period && (
            <View style={styles.metaItem}>
              <Text style={styles.metaLabel}>Period:</Text>
              <Text style={styles.metaValue}>{period}</Text>
            </View>
          )}
        </View>
      )}

      {showDivider && <View style={styles.divider} />}
    </View>
  );
}
