-- ============================================================
-- SEERVIS V2 -- Core Foundation Patch
-- Migration 002: Refinements before domain modules
-- ============================================================
-- This patch refines the core foundation (001) before building
-- domain modules (services, inventory, POS, finance).
-- Changes are based on review gaps identified during architecture planning.
-- ============================================================

-- 1. ADD preferred_brand_id TO profiles
-- ============================================================
alter table public.profiles
  add column if not exists preferred_brand_id integer
  references public.brands(id) on delete set null;

comment on column public.profiles.preferred_brand_id is
  'UX hint for login redirect. NOT permission source of truth. Access is validated through user_brand_memberships.';

create index if not exists idx_profiles_preferred_brand
  on public.profiles(preferred_brand_id)
  where preferred_brand_id is not null;

-- 2. ADD default branch support
-- ============================================================
alter table public.user_branch_access
  add column if not exists is_default boolean not null default false;

create unique index if not exists uq_uba_default_branch
  on public.user_branch_access(membership_id)
  where is_default = true;

comment on column public.user_branch_access.is_default is
  'At most one row per membership_id can have is_default = true. Enforced by partial unique index uq_uba_default_branch.';

-- 3. ADD request_id TO audit_logs
-- ============================================================
alter table public.audit_logs
  add column if not exists request_id uuid;

create index if not exists idx_al_request_id
  on public.audit_logs(request_id)
  where request_id is not null;

comment on column public.audit_logs.request_id is
  'UUID generated by application to group audit entries from one business action.';

-- 4. ENSURE metadata columns are NOT NULL with defaults
-- ============================================================
do $$ begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'payment_accounts'
    and column_name = 'metadata' and is_nullable = 'YES'
  ) then
    alter table public.payment_accounts alter column metadata set default '{}', alter column metadata set not null;
  end if;
end $$;

do $$ begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'payment_account_movements'
    and column_name = 'metadata' and is_nullable = 'YES'
  ) then
    alter table public.payment_account_movements alter column metadata set default '{}', alter column metadata set not null;
  end if;
end $$;

-- ============================================================
-- 5. VALIDATION QUERIES (reference only, not executed)
-- ============================================================

-- 5a. Verify payment_account_movements balance chain consistency
-- Purpose: Detect gaps in before_balance rarr after_balance chain.
-- Expected: Returns 0 rows (no gaps).
--
-- SELECT pam1.id,
--        pam1.payment_account_id,
--        pam1.created_at,
--        pam1.before_balance,
--        pam1.after_balance,
--        prev.after_balance AS previous_after_balance
-- FROM public.payment_account_movements pam1
-- LEFT JOIN LATERAL (
--   SELECT pam2.after_balance
--   FROM public.payment_account_movements pam2
--   WHERE pam2.payment_account_id = pam1.payment_account_id
--     AND (pam2.created_at, pam2.id) < (pam1.created_at, pam1.id)
--   ORDER BY pam2.created_at DESC, pam2.id DESC
--   LIMIT 1
-- ) prev ON true
-- WHERE pam1.before_balance != COALESCE(prev.after_balance, 0);

-- 5b. Verify current_balance matches computed ledger balance
-- Expected: Returns 0 rows (all account balances match).
--
-- SELECT pa.id,
--        pa.account_name,
--        pa.current_balance AS cached_balance,
--        COALESCE(SUM(CASE WHEN pam.direction = 'IN' THEN pam.amount ELSE -pam.amount END), 0) AS ledger_balance
-- FROM public.payment_accounts pa
-- LEFT JOIN public.payment_account_movements pam ON pam.payment_account_id = pa.id
-- GROUP BY pa.id, pa.account_name, pa.current_balance
-- HAVING pa.current_balance != COALESCE(SUM(CASE WHEN pam.direction = 'IN' THEN pam.amount ELSE -pam.amount END), 0);

-- 5c. Verify CASH accounts have correct is_cash_account flag
-- Expected: Returns 0 rows.
--
-- SELECT id, account_name, type, is_cash_account
-- FROM public.payment_accounts
-- WHERE (type = 'CASH' AND is_cash_account = false)
--    OR (type != 'CASH' AND is_cash_account = true);

-- 5d. Verify no active accounts reference deleted branches
-- Expected: Returns 0 rows.
--
-- SELECT pa.id, pa.account_name, b.name AS branch_name, b.deleted_at
-- FROM public.payment_accounts pa
-- JOIN public.branches b ON b.id = pa.branch_id
-- WHERE b.deleted_at IS NOT NULL AND pa.is_active = true;

-- 5e. Verify no duplicate default branches per membership
-- Expected: Returns 0 rows.
--
-- SELECT membership_id, COUNT(*) AS default_count
-- FROM public.user_branch_access
-- WHERE is_default = true
-- GROUP BY membership_id
-- HAVING COUNT(*) > 1;

-- ============================================================
-- 6. EXPLANATION: system cash account unique index
-- ============================================================
-- The index from 001:
--   CREATE UNIQUE INDEX uq_pa_system_cash
--     ON payment_accounts(brand_id, branch_id)
--     WHERE is_system_account = true AND is_cash_account = true AND branch_id IS NOT NULL;
--
-- This enforces "AT MOST ONE" system cash account per (brand_id, branch_id).
-- It does NOT enforce "exactly one." Existence is the responsibility of:
--   a) create_default_cash_account_for_branch() -- called on branch creation
--   b) Seed/init process -- for existing branches
--   c) Application logic -- creating a branch must call this function
--
-- If a row is deleted or deactivated, the constraint allows a new one.
-- It only prevents DUPLICATE system cash accounts.
-- ============================================================


-- ============================================================
-- 7. EXPLANATION: account_sequence for movement ordering
-- ============================================================
-- Tradeoff analysis for adding account_sequence to payment_account_movements:
--
-- WITHOUT account_sequence:
--   + No additional storage (saves 8 bytes per row + index)
--   + Simpler insert function
--   + Ordering uses (created_at, id) with UUID tiebreaker
--   + FOR UPDATE lock in add_payment_account_movement() serializes inserts
--     per account, so created_at collisions are practically impossible
--   - UUID v4 ordering is not strictly chronological as tiebreaker
--   - Cross-account ordering is not deterministic
--
-- WITH account_sequence:
--   + Perfect ordering: 1, 2, 3, ... per account
--   + No tiebreaker ambiguity
--   + Natural index clustering
--   - Requires BIGINT column + per-account counter logic
--   - Adds complexity to add_payment_account_movement() function
--   - Counter reset/overflow considerations
--
-- DECISION: Skip account_sequence for now.
--   The FOR UPDATE lock guarantees serial access per account.
--   Use ORDER BY created_at ASC, id ASC for all movement queries.
--   If ordering issues arise, add account_sequence as a later migration.
-- ============================================================


-- ============================================================
-- 8. SEED DATA PLAN
-- ============================================================
-- Minimal seed for development. NOT a migration.
-- Run separately via psql or Supabase SQL editor AFTER migrations.
-- ============================================================

-- 8a. Platform owner placeholder:
-- 1. Create auth user via Supabase Auth (email+password)
-- 2. Get auth_user_id from auth.users
-- 3. INSERT INTO profiles (auth_user_id, email, name) VALUES ('<id>', 'owner@seervis.com', 'Platform Owner');
-- 4. INSERT INTO user_brand_memberships (profile_id, brand_id, role) VALUES ('<profile_id>', NULL, 'PLATFORM_OWNER');

-- 8b. Demo brand:
-- INSERT INTO public.brands (name, slug, status) VALUES ('Demo Service Center', 'demo', 'active') ON CONFLICT (slug) DO NOTHING;

-- 8c. Demo branches:
-- WITH b AS (SELECT id FROM public.brands WHERE slug = 'demo')
-- INSERT INTO public.branches (brand_id, name, code)
-- VALUES ((SELECT id FROM b), 'Pusat', 'PST'), ((SELECT id FROM b), 'Cabang Utara', 'UTR');

-- 8d. System cash accounts:
-- SELECT public.create_default_cash_account_for_branch(
--   (SELECT id FROM public.brands WHERE slug = 'demo'),
--   (SELECT id FROM public.branches WHERE code = 'PST' AND brand_id = (SELECT id FROM public.brands WHERE slug = 'demo')),
--   'Pusat'
-- );
-- SELECT public.create_default_cash_account_for_branch(
--   (SELECT id FROM public.brands WHERE slug = 'demo'),
--   (SELECT id FROM public.branches WHERE code = 'UTR' AND brand_id = (SELECT id FROM public.brands WHERE slug = 'demo')),
--   'Cabang Utara'
-- );

-- 8e. Payment methods (brand-level):
-- WITH b AS (SELECT id FROM public.brands WHERE slug = 'demo')
-- INSERT INTO public.payment_methods (brand_id, type, name, mdr_percentage, is_active)
-- VALUES
--   ((SELECT id FROM b), 'CASH',     'Tunai',          0,   true),
--   ((SELECT id FROM b), 'QRIS',     'QRIS',           0.7, true),
--   ((SELECT id FROM b), 'TRANSFER', 'Transfer Bank',  0,   true),
--   ((SELECT id FROM b), 'DEBIT',    'Kartu Debit',    1.5, true)
-- ON CONFLICT (brand_id, name) DO NOTHING;

-- 8f. Branch payment method mappings (example for Pusat CASH):
-- INSERT INTO public.branch_payment_methods (brand_id, branch_id, method_type, payment_account_id, is_active)
-- SELECT b.id, br.id, 'CASH', pa.id, true
-- FROM public.brands b, public.branches br, public.payment_accounts pa
-- WHERE b.slug = 'demo' AND br.code = 'PST'
--   AND pa.branch_id = br.id AND pa.is_system_account = true AND pa.is_cash_account = true
-- ON CONFLICT (brand_id, branch_id, method_type) DO NOTHING;

-- ============================================================
-- End of Migration 002
-- ============================================================
